### ISSUE TITLE
Incorrect description of EventBusName

### ISSUE THREAD

**Issue by jyriseiger** [aws-samples/amazon-eventbridge-resource-policy-samples#25]
Incorrect description of EventBusName in [this template](https://github.com/aws-samples/amazon-eventbridge-resource-policy-samples/blob/main/blog/account-c-invoice-processing/template.yaml)  
It's not the name of the central event bus, but invoice processing event bus.

**Comment by sliedig** [comment]
Thanks for submitting this issue, will address this asap!

**Comment by sliedig** [comment]
Resolved. Thank you!
